# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Figuring Things Out Along the Way
email: adam.michael.frank@gmail.
description: "I'm an aspiring software developer and I'm using this site to document my personal projects.  My plan is to write descriptively enough that other new developers can learn from my research and mistakes."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

github_username:  adammfrank

# Build settings
markdown: kramdown
